// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ffqlltuthkpbcjirsjbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmcWxsdHV0aGtwYmNqaXJzamJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0ODgyNjgsImV4cCI6MjA4NjA2NDI2OH0.5BC2GPbGoLPxrHTu1Xy3_2Eldgo6iv92XxqqyUiosCc";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);